### ISSUE TITLE
RTC AL_HEATING_DEMAND vs AL_ACTUATING_VALUE_HEATING

### ISSUE THREAD

**Issue by ML19821** [andrasU/openhab-addons#10]
currently the binding works with
AL_HEATING_DEMAND opd0013 pairing id 333(0x14d)

That works fine for 6 of my 7 RTCs. But at one RTC the value remains always zero. I think this is a Busch Jäger Bug. At this RTC the 
AL_HEATING_ACTIVE  odp0011 pairing id 331(0x14b) remains always zero too. 
I can see this behaviour in this binding, the kjoglums-binding and even at the swagger webinterface.  
The speciality of this RTC ist, that it is connected to my second (6-gang heating actuator). The other 6 are connected to the first one.

The officialBJ support refers to the german support forum, so I tried it here in the german support forum.
https://community.busch-jaeger.de/frage-ansehen/raumtemperaturregler-unterschied-zwischen-al_heating_demand-und-al_actuating_value_heating

Nevertheless I want you to ask, to integrate 
AL_ACTUATING_VALUE_HEATING opd000 pairing id 48(0x30) instead of or in addition to AL_HEATING_DEMAND because only that works for me.
I don't now the difference between AL_HEATING_DEMAND  and AL_HEATING_ACTIVE  but finally i'm interested in the valve.

And I could derive AL_HEATING_ACTIVE  from AL_HEATING_ACTIVE easily, with a JS Transform at chanellevel

Another way could be to let me manipulate the opd/idp channels like in the kjoglums-binding for each thing rsp. channel.

**Comment by andrasU** [comment]
This new channel will be part o the next release, as add-on to the current channels

**Comment by ML19821** [comment]
thank you very much, it works fine.
Here a Screenshot from grafana with booth values
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/96960914/216765910-d7df4cb8-5f92-4621-92e1-18196b2fd2bc.png">
