### ISSUE TITLE
Free@home flex dimmer components recognized without channels

### ISSUE THREAD

**Issue by LtLuckySau** [andrasU/openhab-addons#13]
Hi,

first off: the binding works very well with all my standard free@home switches, temperature controllers and scenes/actions. A big thank you for your awesome work on that!

One of two things i discovered so far that are not working:
my newly installed flex components: i use two flex dimmers combined with motion detectors. These components are recognized in openhab via the binding, but they do appear without channels (no dim actuator, switch on/off or motion detection channels). It would be great to integrate the motion detector and the dimmer as separate channels. Ist that possible?

(This is also connected with my second issue concerning motion detectors, see: https://github.com/andrasU/openhab-addons/issues/12)

**Comment by andrasU** [comment]
Hi @LtLuckySau  

I do not know, whether you tested the latest PRE-version. If yes it could be that the flex devices are handling the pairing ID differently as the RF and Wired ones. Therefore please send me a Swagger JSON output of the device to see what is different.

if you did not run the latest PRE-version, you could find the latest PRE-version under the below link. In this pre version I made some fixes for the dimmer.

[https://github.com/andrasU/openhab-addons/releases/tag/fh-3.4.4-pre4](https://github.com/andrasU/openhab-addons/releases/tag/fh-3.4.4-pre4)

**Comment by LtLuckySau** [comment]
Hi @andrasU 

thank you for the quick reply. I ran the PRE-version as you suggested. While it did not change the behavior of the flex components (dimmers/motion detectors as described here and switch/motion detector as described in ), it changed the behavior of my not-flex dimmers from working with 3 channels (Dim actuator - Absolute Set Value, Dim actuator - Switch On/Off and Control element - Switch On/Off) to Uninitialized with HANDLER_INITIALIZING_ERROR. So i switched back to the version before that. I guess this is a separate issue, which i will gladly give you further feedback on, if you let me know what you need :)

As for the Swagger JSON output: Forgive me, i am fairly new to openhab, so i had to research and take a guess on what you want me to do. I used the API explorer to get the thing via UID and received this output:
```
{
  "channels": [],
  "statusInfo": {
    "status": "ONLINE",
    "statusDetail": "NONE"
  },
  "editable": true,
  "label": "Bewegungsmelder/Dimmaktor 1-fach Flur OG",
  "bridgeUID": "freeathomesystem:bridge:0b53561ae6",
  "configuration": {},
  "properties": {
    "interface": "wireless",
    "modelId": "free@home Device",
    "deviceId": "ABB7030715F4",
    "vendor": "Busch&Jaeger - ABB"
  },
  "UID": "freeathomesystem:free-at-home-device:0b53561ae6:ABB7030715F4",
  "thingTypeUID": "freeathomesystem:free-at-home-device"
}
```

I hope this is what you are looking for. If not, i would be thankful for more instructions. Sorry for my ignorance.

Thank you for looking into this!

**Comment by andrasU** [comment]
Hi @LtLuckySau,

in the pre2 the dimactor with switch and also with dimmer shall work

[https://github.com/andrasU/openhab-addons/releases/tag/fh-v3.4.5-pre2](https://github.com/andrasU/openhab-addons/releases/tag/fh-v3.4.5-pre2)

**Comment by LtLuckySau** [comment]
Hi @andrasU 

I gave the pre2 binary a quick test, the dimmers show up now and work just like the "conventional" free@home dimmers. :)

Thank you very much for your awesome work! I greatly appreciate it!
