### ISSUE TITLE
double Rocker for Rollershutter doesn't work

### ISSUE THREAD

**Issue by ML19821** [andrasU/openhab-addons#15]
I have a double for two rollershutters in my living room.
When I add the double rocker, under channel I only have:
"This thing has no channels. Either the thing type doesn't define channels, or they may be detected and appear later."

currently swagger is unfortunately not working, I always got 
401 Authorization Required

so currently I can not provide a json of the double rocker.

**Comment by ML19821** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/96960914/229375361-8b88778e-1f78-49f6-b226-ca58d6109baf.png">

**Comment by andrasU** [comment]
Sorry for the late answer. Your rollershutter is controlled by one sensor only device, the actor is not inside the device. Therefore the this device is not having the feedbsck where the Blind is. This device can only control the movement up/down and command stop to the rollershutter. The rollershutter position shall be available from the rollershutter actor.

**Comment by ML19821** [comment]
Yes, you're right. 
What I want is to intercept a double click within one second, but this is only possible if I configure the double rocker as a double switch within the Free@Home system, then it will be recognised as having two "switch" channels.

But then I'll lose the original Free@Home function, which distinguishes between a short press(short shutter movement) and a long press (full shutter movement).

There would be no solution for this.
Let us close this issue here.
