### ISSUE TITLE
Wether station does not provide values

### ISSUE THREAD

**Issue by andrasU** [andrasU/openhab-addons#5]
## Expected Behavior
The brightness sensor and the outside temperature sensor channel shall provide for the virtual Wether station real values

## Current Behavior
Currently Brightness Alarm and Temperatur Sensor are not working in the binding

**Comment by KKlausl** [comment]
Brightness Sensor, Brightness Alarm and Temperatur Sensor working fine for me. No Problems whatsoever.
<img width="816" alt="Unbenannt2" src="https://user-images.githubusercontent.com/78704429/213803610-8ecdf065-5b9a-44b7-b86c-8046f4066515.png">
<img width="821" alt="Unbenannt" src="https://user-images.githubusercontent.com/78704429/213803612-3e2972cf-c0e2-4540-b840-9cebe795be85.png">

**Comment by andrasU** [comment]
Wether station fix is implemented in the below pre-release. 

[fh-3.4.4-pre3](https://github.com/andrasU/openhab-addons/releases/tag/fh-3.4.4-pre3)
