### ISSUE TITLE
Rollershutter Icons in Free@home Next app is not 

### ISSUE THREAD

**Issue by sleugner** [andrasU/openhab-addons#7]
## Expected Behavior

The Icon of a Rollershutter in the Free@Home Next app should represent the Status of the  Rollershutter.

## Current Behavior

Rollershutter Icon in the App does not change. The Percentage of the Rollershutter Status shows the right value.
![Unbenannt](https://user-images.githubusercontent.com/123119066/213568072-9adb293e-b8a4-4d50-b535-3fd9cf5bd5a1.PNG)

If an Rollershutter is connected to a Widget in Open hab it is not possible to calibrate the Rollershutter.
The Values are not safed and there are only Questionmarks in the Icon.
If the Rollershutter is not connected to an Widget calibration is working fine.
![Unbenannt1](https://user-images.githubusercontent.com/123119066/213568255-3f5ade2a-a474-4eef-bbbb-cf78ffc0b81a.PNG)

I used the uid: universal_shutter_v4 from the marketplace:116270

## Possible Solution

Maybe Icon has to be connected to the "Set Absolut Position Blinds" Channel.
With calibration no Idea.

## Steps to Reproduce (for Bugs)

1. Connect Rollershutter Aktor Channels to an Widget
2. Controlle the Rollershutter
3. Look into the app 

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
Release fh-v3.4.3 
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
Raspbian

**Comment by KKlausl** [comment]
Using no widget - calibration is working fine for me also.
<img width="291" alt="123" src="https://user-images.githubusercontent.com/78704429/214398457-09b7f13f-dbef-49c2-a2a6-b8b531ed62b3.png">

**Comment by sleugner** [comment]
I think this might have been an issue from F@H because it was also not working with the Iphone Widget.
Everything is working fine with the new binding "fh-3.4.4-pre4".
Thanks

**Comment by andrasU** [comment]
Working since 3.4.4-pre4
